name: syntax-check
on:
  pull_request:
    branches:
      - 'master'
      - 'dev'
    types: [opened, reopened, edited, synchronize]
    paths:
      - 'serverless.yml'
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_KEY_SECRET }}
  ES_ID: ${{ secrets.ES_ID }}
  ES_SECRET: ${{ secrets.ES_SECRET }}
  ES_ENDPOINT: ${{ secrets.ES_ENDPOINT }}
  STOCKS_BUS_ARN: ${{ secrets.EB_STOCKS_BUS_ARN }}
jobs:
  syntax-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: npm i
    - name: serverless syntax check
      uses: serverless/github-action@master
      with:
        args: deploy --noDeploy
